remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Mauw94's JS dog/cat breed detector
description: Bookmark this to keep an eye on my project updates!

author:
  name: Maurits Seelen

